/* THIS FILE IS AUTOMATICALLY GENERATED */
char *BuildSystem= "Linux EASYPC22412 5.15.79 #1 SMP Sat Nov 26 10:32:41 +08 2022 x86_64 x86_64 x86_64 GNU/Linux";
char *BuildDate= "Mon Jan 23 11:28:30 AM +08 2023";
char *BuildUser= "uid=0(root) gid=0(root) groups=0(root),2(bin),70(scanner),99(kvm),100(disk),101(audio),102(lp),103(dialout),104(kmem),105(video),106(floppy),107(cdrom),108(tape),110(plugdev),111(wheel),112(lpadmin),114(shutdown),115(crontab),116(pulse),117(pulse-access),118(fscryptgrp),120(bluetooth),121(rtkit),122(filesgrp)";
